### ISSUE TITLE
support erb interpolation in skylight.yml

### ISSUE THREAD

**Issue by janvarljen** [skylightio/skylight-ruby#28]
I wanted to read tokens from my secrets.yml file, this way:

```yml
// skylight.yml

# The Skylight ID for the application.
application: <%= Rails.application.secrets.skylight['application'] %>

# The authentication token for the application.
authentication: <%= Rails.application.secrets.skylight['authentication'] %>
```

but it's not possible because you don't process ERB on YAML load.

If you think this could be added, let me know and I'll PR
